CREATE TABLE item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    sku VARCHAR(40) NOT NULL UNIQUE,
    category VARCHAR(60) NOT NULL,
    quantity_on_hand INT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE
);

INSERT INTO item (name, sku, category, quantity_on_hand, active) VALUES
    ('Laptop', 'IT-1001', 'Electronics', 8, TRUE),
    ('HDMI Cable', 'IT-1002', 'Cables', 25, TRUE),
    ('Office Chair', 'FN-2001', 'Furniture', 4, TRUE);
