CREATE TABLE checkout (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id BIGINT NOT NULL,
    borrower_name VARCHAR(120) NOT NULL,
    borrower_email VARCHAR(180) NOT NULL,
    quantity INT NOT NULL,
    due_date DATE NOT NULL,
    returned_at TIMESTAMP,
    checked_out_by VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_checkout_item FOREIGN KEY (item_id) REFERENCES item (id)
);

-- Demo overdue loan so the dashboard is not empty on first run.
INSERT INTO checkout (
    item_id, borrower_name, borrower_email, quantity, due_date,
    returned_at, checked_out_by, created_at
)
SELECT id, 'Alex Rivera', 'alex@example.com', 2, DATEADD('DAY', -3, CURRENT_DATE),
       NULL, 'staff', CURRENT_TIMESTAMP
FROM item
WHERE sku = 'IT-1002';

UPDATE item
SET quantity_on_hand = quantity_on_hand - 2
WHERE sku = 'IT-1002';
